# Generated by Django 2.0.1 on 2018-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flagIn',
            field=models.CharField(choices=[('Platfom to Outside', 'Outside to Platform')], default='Platform to Outside', max_length=30),
        ),
    ]
