# Generated by Django 2.0.1 on 2018-10-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolie', '0002_booking_flagin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail', models.BooleanField(default=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolie.Employee')),
            ],
        ),
    ]
