# Generated by Django 2.0.1 on 2018-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolie', '0003_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profilePic',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
