# Generated by Django 2.0.1 on 2018-10-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolie', '0011_auto_20181021_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='empId',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='locId',
            field=models.CharField(max_length=300),
        ),
    ]
