# Generated by Django 2.0.1 on 2018-10-21 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolie', '0012_auto_20181021_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolie.Employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='locId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolie.Location'),
        ),
    ]
