# Generated by Django 2.0.1 on 2018-10-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolie', '0013_auto_20181021_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dropTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickupTime',
        ),
    ]
